### ISSUE TITLE
Feature Request: Sync file(s) across repositories 

### ISSUE THREAD

**Issue by StevenACoffman** [lindell/multi-gitter#11]
Currently we have identical files in multiple repositories (protobuf definitions) and when we make a change in one repository, we would like to make the identical change in the other repository. The directory in one repo is not the same as the directory in the other repository.

Multi-gitter would be even more useful if it could automate this for us. Thanks for a cool tool regardless!

**Comment by lindell** [comment]
Is the intention to run it when the change is done in any of the repositories or would it be ok to have a "main" protobuf definition repo and sync it from there?
The first one would probably be more tricky, but the second should be possible 🙂

**Comment by StevenACoffman** [comment]
Generally having a main repository as the authoritative "single source of truth" repository would work fine for us! We can put a comment in most files to tell people only to edit it in the origin repository.

**Comment by lindell** [comment]
A script like this

```bash
#!/bin/bash

dir=`find . -name ".protobuf" | xargs -I{} dirname {}`

if [ -z "$dir" ]
then
    echo "could not find a protobuf folder"
    exit 1
fi

rm -rf $dir
cp -R /path/to/protobuf/defs $dir
```

Assuming that the file `.protobuf` exist in the folder. This way the script can find the folder no matter where it exists 🙂 
You can ofc just use a name of one of the protofbuf files instead.

Try running with the `--dry-run` (and maybe `--log-level info`) if you want to test it out.

It should be easy to just run it in the CI-environment of your choice when changes are done in the authoritative protobuf dir 😄

**Comment by lindell** [comment]
I was very curious how this would actually work so I tried implementing it on a test organization. 
https://github.com/sync-test

Making this change https://github.com/sync-test/definitions/commit/5a768e509dbded8bf32339fb1fb3f1bf441a5dc7

Triggered these two PRs:
https://github.com/sync-test/service-1/pull/1
https://github.com/sync-test/service-2/pull/1

I took some "shortcuts", like installing from source etc. But the same approach should work 🙂

**Comment by StevenACoffman** [comment]
That's awesome! Thanks so much!
