### ISSUE TITLE
Fork mode

### ISSUE THREAD

**Issue by lindell** [lindell/multi-gitter#124]
Add the ability to fork the repository and make the changes on the fork instead of only allowing on a branch in the same repo.

The owner of the fork should probably be an option since you can fork both under your own name and under an organization. 

This ticket was created after some discussions on #122

**Comment by lindell** [comment]
A first draft with GitHub support can be found here:
https://github.com/lindell/multi-gitter/pull/128

@dorner

**Comment by dorner** [comment]
@lindell did a quick test and it looks like it works! Amazing!

**Comment by lindell** [comment]
Released with [v0.27.0](https://github.com/lindell/multi-gitter/releases/tag/v0.27.0) 🎉

**Comment by dorner** [comment]
Yahoo!
