### ISSUE TITLE
Gitlab: Does not support nested groups

### ISSUE THREAD

**Issue by tyronedd** [lindell/multi-gitter#170]
**Describe the bug**
When using the `project` attribute in the yaml config or on the command line it does not support sub-groups on GitLab.

When running a config that has: 

```yaml
project:
  - group-org/subgroup/project
```

It fails with the following message:

`could not parse repository reference: group-org/subgroup/project`

Looking through the code it seems that it fails on this validation function:

https://github.com/lindell/multi-gitter/blob/cb4701eb90b98bf585b1a8835368c4cd8f0e0095/internal/scm/gitlab/gitlab.go#L70-L80

It splits on slashes and errors when the parts are not equal to `2`.

Changing the second slash to URI encoded slash (`group-org/subgroup%2Fproject`) allows me to pass the validation function but then it errors when actually trying to fetch the repository.

**Expected behavior**
I'd expect it to allow projects in nested groups on Gitlab.

Hope this is clear enough! Nice tool BTW! 👍🏾

**Comment by tyronedd** [comment]
Damn, that's superfast, thanks! Did a very quick test with one nested project and it created a pull request!

Tomorrow I'll test it some more since I need to roll out some changes over multiple repo's.

**Comment by lindell** [comment]
Perfect 👍 

This fix is now release with [v0.31.1](https://github.com/lindell/multi-gitter/releases/tag/v0.31.1)

**Comment by lindell** [comment]
May I also ask what script you executed? :) And also how you found this repo

**Comment by tyronedd** [comment]
> May I also ask what script you executed? :)

Yeah sure no problem!

```bash
#!/bin/bash
tf_file_present=$(find "." -name "*.tf")


if [[ ! -z "$tf_file_present" ]]; then
    echo "Terraform files detected!"
  else
    echo "Not a Terraform repository, exiting"
    exit 0;
fi

for tf_file in $tf_file_present; do
  if grep -q "password" $tf_file && grep -q "backend" $tf_file; then
    echo "Found a candidate file for backend configuration: $tf_file"
    echo "Attempting to remove 'password' and 'username' from Backend config"
    
    hcledit -f $tf_file --update attribute rm terraform.backend.http.password
    hcledit -f $tf_file --update attribute rm terraform.backend.http.username
  fi
done
```

context: I used backend config with placeholders in Terraform which takes precendence over configuration with environment variables, which I now want to use. So I have to remove those entries.

I actually hacked together a repo to run this in Gitlab CI, not sure if it's useful yet: https://gitlab.com/el-capitano/tools/multi-gitter

> And also how you found this repo

Had to go back a bit in my history, but I knew about [SourceGraph Batch Changes](https://docs.sourcegraph.com/batch_changes), which seems to work the same, but way more features. But also way too much for my use case I have right now so:

1. I searched for https://www.google.com/search?q=apply+changes+to+multiple+repositories
2. Which let me to this blogpost https://dev.to/lindell/make-bulk-changes-over-multiple-repositories-27i9, which I can now see is yours 😄

**Comment by lindell** [comment]
Thanks for the description of how you used multi-gitter and how you found it 🙂 I'm trying to understand use cases, to better understand possible improvement, etc.
