### ISSUE TITLE
Error after merging a Github repo

### ISSUE THREAD

**Issue by marksmithson** [lindell/multi-gitter#188]
**Describe the bug**
When merging a GitHub repository which is set to "Automatically delete head branches" a 422 Reference does not exist [] error is returned and processing of repositories is halted

**To Reproduce**
1. Create a repo which has "Automatically delete head branches"  in Options
2. Run `multi-gitter merge -xxx`
3. See error - this does not happen on all runs - I think this depends on timing

**Expected behavior**
The 422 error is caught and ignored. Processing of repositories continue

**Comment by lindell** [comment]
Thanks for the bug report and the clear description and reproduce steps 🙂 

This should now be fixed in [v0.33.2](https://github.com/lindell/multi-gitter/releases/tag/v0.33.2)
