### ISSUE TITLE
Add flag to update a pull request thats already opened

### ISSUE THREAD

**Issue by ChaosCypher** [lindell/multi-gitter#205]
After I've run multi-gitter and opened my prs, it would be great to have the ability to update my pr in the scenario where maybe I've missed something, or make a mistake and need to update.

Something like a 'multi-gitter run --update-pr`

**Comment by lindell** [comment]
I've added `--conflict-strategy` and implemented `skip` (default and previous behaviour) and `replace`.

Please install it with `go install github.com/lindell/multi-gitter@conflict-strategy-2`, try it, and report back if it works as intended.

**Comment by ChaosCypher** [comment]
Hello,

This is working great, and as intended.
