### ISSUE TITLE
Support for Repo's SSH URL

### ISSUE THREAD

**Issue by nicely-dunn** [lindell/multi-gitter#214]
Hi there, 
I was looking to use this tool as a quick way to update the reference version of CI templates in GitLab across multiple repos, as GitLab doesn't allow for variables to be set in the ref and I don't want to have all my repos reference the master branch.
My repos' `gitlab-ci.yml` looks something like this:
```yaml
include:
  - project:  "templates/gitlab-ci"
    ref:      "v2.3.1" # can also be a branch name - variables do not expand here
    file:     "helm.yml"
```
However I've run into an issue - I cannot use the HTTP URL to clone a repo.

To give a little backstory on this, I work in a self-hosted GitLab environment that has the HTTPS URL disabled (and I'm not in charge of the platform so it can't be enabled), meaning that whenever I try to use multi-gitter I get a permission denied when it goes to clone a repo because it's reliant on the HTTPS URL. I thought I could maybe get around this by defining in git something like:
```bash
git config --global url."git@private.gitlab.com:".insteadOf "https://private.gitlab.com/"
```
and switching the multi-gitter config to use `git-type: cmd`, but it seems like however multi-gitter is calling git ignores this setting.

I'm wondering if it would be possible to add an option for use of the SSH URL instead of the HTTP URL to clone a repo when using the run command. My Golang knowledge isn't very strong but I poked around in the code and it seems like in the `convertProject` function in `internal/scm/gitlab/repository.go` explicitly uses `project.HTTPURLToRepo` as the source for its clone URL.

Trace of when I try to use run command:
```
multi-gitter run ./update_gitlab_template_ref.sh --config=./config.yaml
...
INFO[0000] Running on 1 repositories                    
INFO[0000] Cloning and running script                    repo=helm/postgresql
INFO[0000] could not clone from the remote: authorization failed  repo=helm/postgresql
TRAC[0000] github.com/lindell/multi-gitter/internal/git/gogit.(*Git).Clone
	/home/runner/work/multi-gitter/multi-gitter/internal/git/gogit/git.go:36
github.com/lindell/multi-gitter/internal/multigitter.(*Runner).runSingleRepo
	/home/runner/work/multi-gitter/multi-gitter/internal/multigitter/run.go:207
github.com/lindell/multi-gitter/internal/multigitter.(*Runner).Run.func2
	/home/runner/work/multi-gitter/multi-gitter/internal/multigitter/run.go:118
github.com/lindell/multi-gitter/internal/multigitter.runInParallel.func1
	/home/runner/work/multi-gitter/multi-gitter/internal/multigitter/run.go:169
runtime.goexit
	/opt/hostedtoolcache/go/1.17.2/x64/src/runtime/asm_amd64.s:1581 
Could not clone from the remote: authorization failed:
  helm/postgresql
```

**Comment by lindell** [comment]
I did not know that you could disable HTTP(s) logins, and that will indeed break multi-gitter. The idea with using it is that only the token should need to be provided, and nothing else. 

The easy part should be to fetch the SSH URL, the harder will be to make sure it works in all scenarios, like private keys with passwords etc.

I've started to work on this branch: https://github.com/lindell/multi-gitter/pull/215
It seems to work under some specific conditions:
* GitHub/GitLab
* `--git-type=cmd` is used
* The private key does not have a password, unless you want to input it two times for every repo

Please install it and confirm if it works for you under these scenarios
```
go install github.com/lindell/multi-gitter@ssh-auth
```

**Comment by nicely-dunn** [comment]
Didn't expect to come back to something to work with first thing Monday, this is amazing.
This works for my use case quite nicely (though embarrassingly it took me way to long to realize I had forgotten to add `ssh-auth: true` to my `config.yaml` when I first went to test it). 

I forgot to add that I gpg sign my commits, it asked me for the password the first time it creates an MR and the rest of the time it holds it in memory, just as an FYI for behaviour.

Thanks very much for your quick help!
