### ISSUE TITLE
Support GitHub App Tokens

### ISSUE THREAD

**Issue by AWNCypher** [lindell/multi-gitter#223]
**Describe the bug**
It would be great if this tool supported GitHub Apps (https://docs.github.com/en/developers/apps/building-github-apps/authenticating-with-github-apps), rather than having to use a PAT tied to a specific user, one could implement "bot" like behaviours. An installation token provided by the github app is very similar to a users PAT, and could be run from github actions. Right now when running multi-gitter with `trace` debugging, I can see it can read all of the repos in an org, but it won't open any PRs.

**To Reproduce**
1. Install a github app in an organization 
2. Retrieve an installation token from the app
3. Use the installation token with multi-gitter

**Additional context**
```2022-01-25T05:46:32.0829389Z {
2022-01-25T05:46:32.0830234Z   "host": "api.github.com",
2022-01-25T05:46:32.0830929Z   "level": "trace",
2022-01-25T05:46:32.0831238Z   "msg": "http request",
2022-01-25T05:46:32.0832527Z   "request": "GET /orgs/xxxxx/repos?page=1\u0026per_page=100 HTTP/1.1\r\nHost: api.github.com\r\nUser-Agent: go-github\r\nAccept: application/vnd.github.mercy-preview+json, application/vnd.github.nebula-preview+json\r\nAccept-Encoding: gzip\r\n\r\n",
```

⏫  returned all of the repos I was expecting

```2022-01-25T05:46:36.0066918Z {
2022-01-25T05:46:36.0067099Z   "level": "info",
2022-01-25T05:46:36.0067356Z   "msg": "Running on 0 repositories",
2022-01-25T05:46:36.0067650Z   "time": "2022-01-25T05:46:35Z"
2022-01-25T05:46:36.0067851Z }
```

But it ran against none of them. If I switch to a PAT, this works as expected but isn't ideal for large workloads.

**Comment by lindell** [comment]
Does the token have write access?

Please include the permissions part of one of the repos in the `GET /orgs/xxxxx/repos` request.

Example:
```json
        "permissions": {
            "admin": false,
            "maintain": false,
            "push": true,
            "triage": true,
            "pull": true
        }

```

**Comment by lindell** [comment]
If you have set it using `--token` it should always use that. 

So as of now, this does not no seem to be a problem with multi-gitter. I will close this issue, but if you find something else, please free to reopen or open another issue.

**Comment by AWNCypher** [comment]
Hello,

Would it be possible to provide additional logging information when multi-getter runs against zero repositories?

I’ve engaged GitHub support to assist, but it’s difficult to troubleshoot when multi-gitter runs “successfully” against nothing.

From: Johan Lindell ***@***.***>
Date: Wednesday, January 26, 2022 at 2:16 AM
To: lindell/multi-gitter ***@***.***>
Cc: Jamie Sadler ***@***.***>, Author ***@***.***>
Subject: [External] Re: [lindell/multi-gitter] Support GitHub App Tokens (Issue #223)

[External]

If you have set it using --token it should always use that.

So as of now, this does not no seem to be a problem with multi-gitter. I will close this issue, but if you find something else, please free to reopen or open another issue.

—
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flindell%2Fmulti-gitter%2Fissues%2F223%23issuecomment-1021929056&data=04%7C01%7Cjamie.sadler%40arcticwolf.com%7Cde13b7c07c184249d20908d9e09bd35a%7C066bffccc53d4584a5b79b9b750f7b29%7C0%7C0%7C637787782150002274%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1sRJvuOj8ud2QrjG7erb358Krlz47yCdLqLwu8hD2io%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUYOBSKHL4C6APPMFHP6V23UX6NWHANCNFSM5MXKVVYA&data=04%7C01%7Cjamie.sadler%40arcticwolf.com%7Cde13b7c07c184249d20908d9e09bd35a%7C066bffccc53d4584a5b79b9b750f7b29%7C0%7C0%7C637787782150002274%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=da%2BBjyYqi0QSKAW0XTRh7EZn7IAIsvZZj27H9e6SJJc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjamie.sadler%40arcticwolf.com%7Cde13b7c07c184249d20908d9e09bd35a%7C066bffccc53d4584a5b79b9b750f7b29%7C0%7C0%7C637787782150002274%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=gY51z9GQogi2tpWkxi2CyufA6NuIKzaJSanoXPGiAQo%3D&reserved=0> or Android<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjamie.sadler%40arcticwolf.com%7Cde13b7c07c184249d20908d9e09bd35a%7C066bffccc53d4584a5b79b9b750f7b29%7C0%7C0%7C637787782150002274%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mIVRVKWaAOLIxCtRXLeqSrwLWEOrhqU36egM9m90Xas%3D&reserved=0>.

**Comment by AWNCypher** [comment]
@lindell I did some testing today and I was able to create a PR with the token using curl.

**Comment by lindell** [comment]
And what is shown when you list repos in the org?
It seems that the correct token is not used. Please verify that you are using the correct token.

**Comment by lindell** [comment]
Better message with zero repositories is something that will be added.
