### ISSUE TITLE
Add run option to tell multi-gitter to create PR in draft mode

### ISSUE THREAD

**Issue by maxenglander** [lindell/multi-gitter#225]
It would be nice if `multi-gitter` run had a `--draft` option to create GH PRs in draft mode. This is useful in case the run script doesn't support some edge case in one of the repos, and we can spot check PRs before marking them ready-for-review.

**Comment by lindell** [comment]
This is indeed something that should be added. If you want to contribute, it should be an easy addition, since it's mostly adding propagating the flag down to:
![image](https://user-images.githubusercontent.com/284868/151500189-051fbb41-9f05-461a-82b4-307bef20d8a0.png)

https://pkg.go.dev/github.com/google/go-github/v42/github#NewPullRequest
https://github.com/lindell/multi-gitter/blob/master/internal/scm/github/github.go#L272

**Comment by tmeijn** [comment]
Questions I have here: 
* how should `merge` behave? Should it ignore draft Pull Requests or should it modify draft status and merge anyway? 
* I assume if Pull Requests are created as draft, you'd also want to un-mark them as draft with Multi-Gitter. Is it currently possible to update a Pull Request with Multi-Gitter?

**Comment by lindell** [comment]
* Great question. I'm actually not sure about the answer. Maybe @maxenglander can describe his intended usecase with this feature to give some insight. 
* There is currently nothing that's updating the PR/MR data. I'm not sure that's strictly necessary for this to be implemented, it all depends on how it's intended to be used.

**Comment by maxenglander** [comment]
@lindell @tmeijn

 * I was not envisioning the `merge` command changing/merging draft PRs. I am fine with keeping whatever the current behavior of the `merge` command with respect to draft PRs.
 * For my purposes, having the ability to unmark draft isn't necessary.

It would be nice to have either of those options (merge draft, unmark draft), but I will be satisfied with just the ability to create PRs in draft mode.

**Comment by lindell** [comment]
@tmeijn Then let's start with simply changing the creation behaviour of `run` 🙂

**Comment by maxenglander** [comment]
Thank you @lindell and @tmeijn for the quick turn-around! Excited to use this :)
