### ISSUE TITLE
GitLab 14.10.2: 401 Unauthorized

### ISSUE THREAD

**Issue by wilricknl** [lindell/multi-gitter#250]
**Describe the bug**

Running multi-gitter against a self-hosted GitLab server fails after upgrade from GitLab 14.9.3 to 14.10.2. I wrote a script to update multiple projects and did a dry-run to confirm it all works. Due to a deadline the update had to wait and didn't get applied, while an upgrade to the GitLab server was applied in the meantime. The script is unchanged, but all of a sudden I can't access any GitLab project anymore through multi-gitter.

**To Reproduce**

1. Run `multi-gitter run "python3 $PWD/change.py" --config spec.yaml --project owner/myproj --reviewers rev1,rev2,rev3 --assignees as1`
3. Returns `could not fetch repositories: GET https://self.hosted/api/v4/projects/owner/myproj: 401 {message: 401 Unauthorized}`

**Expected behavior**

I expect to be able to run the change and create a merge request as specified in the YAML. 

**Additional context**

Cloning using the Personal Access Token from command line as follows `git clone https://oauth2:<token>@self.hosted/owner/myproj.git` also works just fine. So the Personal Access Token seems to work, except in combination with multi-gitter. Which made me clueless where this error originates.

**Comment by lindell** [comment]
It seems to not be the cloning that fails, but the fetching of extra information about the project via a GET request. Can you try to manually do the get request that fails. If that does work, please provide trace logs from the run.

**Comment by wilricknl** [comment]
My script used to rely on `GITLAB_TOKEN` to be in the environment variables, but by specifying the token as an argument `multi-gitter print "./change.sh" -T <TOKEN>` everything seems to work again. Thanks for your time and this amazing tool!
