### ISSUE TITLE
Need to push changes only to specific repos under an org -

### ISSUE THREAD

**Issue by arun291091** [lindell/multi-gitter#253]
@lindell    I tried using the --repo option but it still pushes to all the repos under that org.. i am i missing something ?

arunk@hjgj7m3:~/personal$ multi-gitter run ./script.sh -O arun-291091 -m "testing" -b main --repo=arun-291091/semgrep --skip-pr=true
INFO[0000] Running on 4 repositories
INFO[0000] Cloning and running script repo=arun-291091/test-1
INFO[0001] Pushing changes to remote repo=arun-291091/test-1
INFO[0002] Cloning and running script repo=arun-291091/test-2
INFO[0003] Pushing changes to remote repo=arun-291091/test-2
INFO[0004] Cloning and running script repo=arun-291091/test-3
INFO[0005] Pushing changes to remote repo=arun-291091/test-3
INFO[0006] Cloning and running script repo=arun-291091/semgrep
INFO[0006] Pushing changes to remote repo=arun-291091/semgrep
Repositories with a successful run:
arun-291091/test-1
arun-291091/test-2
arun-291091/test-3
arun-291091/semgrep

**Comment by lindell** [comment]
You are defining to both include everything under `arun-291091/*` and to specifically include `arun-291091/semgrep`. If you don't want everything under the `arun-291091` org, simply remove the `-O arun-291091` and just use `--repo=arun-291091/semgrep`

**Comment by arun291091** [comment]
Thank you , it worked.. is there a possibility of adding a regex... like the following for the repos ? or i have to add all the repos separated by commas ?

 multi-gitter run ./script.sh -O arun-291091 -m "testing" -b main --repo=arun-291091/test-* --skip-pr=true

**Comment by lindell** [comment]
No regexp option does exist. But you could add a filtering to the script based on the $REPOSITORY variable.

**Comment by arun291091** [comment]
Do you mind sharing a sample on how to use that ?
