### ISSUE TITLE
Cannot create PR in Github enterprise instance.

### ISSUE THREAD

**Issue by Mseller** [lindell/multi-gitter#256]
**Describe the bug**
No PR is created when running `multi-gitter run ...` in our GitHub enterprise instance. The following error is produced `json: cannot unmarshal array into Go value of type github.PullRequest`. This happens for all repos within the organization, and not only for a specific one.

**To Reproduce**
1. Try to create a PR on a GitHub enterprise instance.
2. Run `multi-gitter run ./upgrade-deps.sh -O <MY_ORGANISATION> -m "Upgraded dependencies and go version" -B upgrade-dependencies -g http://<GITHUB_ENTERPRISE_URL> --conflict-strategy replace`
3. It produces the error `json: cannot unmarshal array into Go value of type github.PullRequest`

**Expected behavior**
I expect PRs to be created for each change in each repo.

**Context**
The version of the GitHub enterprise version is currently `3.3.1`

**Comment by lindell** [comment]
Hi and thanks for the detailed report.
As you alluded to, I think this is a change that needs to be made in the go-github package. Please create a issue there, Iäm happy to be a part of that discussion.

Do you know when this change happened, and if it is intended to come to none enterprise GitHub? The link in the updated code does 404 for me (https://docs.github.com/en/free-pro-team@latest/rest/reference/pulls/#create-a-pull-request)

**Comment by Mseller** [comment]
I did some further investigation on this, and what happens is that when the PR is created, I get back a list of PRs (as if the endpoint `GET /repos/{owner}/{repo}/pulls` was called). However, that list only includes _another_ open PR, not the one I actually created via the script. This is super weird. So I am not sure if it is actually a problem with the github package itself or our Enterprise instance.

Ahh, sorry about that, I also tried to upgrade the `github.com/google/go-github` package to see if that was the issue, so the change code is actually using version `v45.2.0`. However, from my use case above, there was no difference between the two versions.

**Comment by Mseller** [comment]
Created an issue in `https://github.com/google/go-github`: https://github.com/google/go-github/issues/2402

**Comment by lindell** [comment]
Any updates on this? Did you figure out why your instance returned an array?

**Comment by Mseller** [comment]
Sorry, I have been on vacation for 5 weeks, so I have not had time to look into this further. However, I believe we can safely say that the issue I am having is not due to this service, so I can close this issue 😄
