### ISSUE TITLE
Unable to commit to main branch with 'confict-strategy=replace' "A branch named 'main' already exists.

### ISSUE THREAD

**Issue by evoicefire** [lindell/multi-gitter#278]
**Describe the bug**

Even with conflict strategy set to 'replace' I still cannot get multi gitter to create a commit directly to main.

**To Reproduce**
1. Run multi-gitter with branch set to 'main' and conflict-strategy set to replace with dry-run=true
```
multi-gitter run -B main -L debug --dry-run=true --repo <redacted> --conflict-strategy=replace --commit-message=TEST --git-type=cmd ./update_namespace.sh
INFO[0000] Running on 1 repositories                    
INFO[0000] Cloning and running script                    repo=<redacted>
INFO[0001] A branch named 'main' already exists.         repo=<redacted>
A branch named 'main' already exists.:
  <redacted>
```

**Expected behavior**

Multi gitter to display the diff between current main and proposed changes.

**Additional context**
I have tried with both types of git (cmd and go) with the same result. I have also tried setting the configuration from the config.yml and the command line options.

Any help much appreciated :)

**Comment by lindell** [comment]
Hello.If you intend to not create a PR, but instead push the changes directly to the main branch, please use the option
```
      --skip-pr                    Skip pull request and directly push to the branch.
```

But a better error message that it's not possible to create a branch that is the same as the default one should be added.

**Comment by evoicefire** [comment]
Ah, perfect thanks a lot. Sorry, it seems very obvious now.
