### ISSUE TITLE
Add ability to configure repository clone directory (currently system temp)

### ISSUE THREAD

**Issue by Sam13** [lindell/multi-gitter#294]
I'm running multi-gitter inside a Docker / VS Code devcontainer environment.
It would be nice to configure the directory where multi-gitter clones the repositories.
Currently this is the system temporary directory:
https://github.com/lindell/multi-gitter/blob/c12fb13b4889e174c684f0fc1ef46b52b5462a67/internal/multigitter/run.go#L202

This would allow mounting a Docker volume and examine the GIT changes in interactive mode with a GIT GUI of choice on the Docker host.
Currently I have to map the system temporary directory to the Docker host which is not nice.

**Comment by lindell** [comment]
I would merge a PR if this where added :) `--tmp-dir` might be a good option name?

**Comment by Sam13** [comment]
Sorry, I have no Go knowledge :-|

Maybe ```--clone-directory``` fits better?

**Comment by lindell** [comment]
> Maybe --clone-directory fits better?

Agree.

I'm happy to provide constructive feedback on the PR, no matter if the initial iterations will be non-idiomatic, etc.
