### ISSUE TITLE
Installation fails with 404 on Windows

### ISSUE THREAD

**Issue by fabasoad** [lindell/multi-gitter#306]
**Describe the bug**
Installation fails with `404` on Windows.

**To Reproduce**
1. On Windows run the command below.

```shell
curl -s https://raw.githubusercontent.com/lindell/multi-gitter/master/install.sh | sh -s -- -d v0.43.1
```

2. See the following log output:

```text
lindell/multi-gitter info checking GitHub for tag 'v0.43.1'
lindell/multi-gitter debug http_download https://github.com/lindell/multi-gitter/releases/v0.43.1
lindell/multi-gitter info found version: 0.43.1 for v0.43.1/Windows/x86_64
lindell/multi-gitter debug downloading files into /tmp/tmp.sxZiG8SCnq
lindell/multi-gitter debug http_download https://github.com/lindell/multi-gitter/releases/download/v0.43.1/multi-gitter_0.43.1_Windows_x86_64..exe
lindell/multi-gitter debug http_download_curl received HTTP status 404
```

**Expected behavior**
Installation should passed successfully

**Additional context**
Probably it happens because of [L105](https://github.com/lindell/multi-gitter/blob/master/install.sh#L105) that is changing format to `.exe` but all assets in release are in `.tar.gz` format.

**Comment by lindell** [comment]
Hello! Honestly, I did not intend for this installation method to be used by Windows users. Having `sh` installed can't be super common?

Ofc if we can get it to work, it would be great! 😄 
I think your observation about the .exe renaming is correct. But there should be other problems such as the installation directory. `/usr/local/bin` does not exist in windows, and there exists nothing similar except `C:/Windows/System32`, which is not really intended to install external programs?

But as a start, could you make this change locally and run it with `cat install.sh | sh -s -- -d`
