### ISSUE TITLE
Gitlab: Groups need to be urlencoded

### ISSUE THREAD

**Issue by syphernl** [lindell/multi-gitter#329]
**Describe the bug**
Previously we could run multi-gitter like this:

```yaml
group: 
  - team/project1
  - team/project2
```

We haven't ran this tool in a few months but now with multi-gitter 0.44.0 / Gitlab 15.9 this (now) results in:

```
could not fetch repositories: GET https://gitlab.example.com/api/v4/groups/team/project1/projects: 404 {message: 404 Group Not Found}
```

Visiting this URL indeed shows a 404. 

* If I replace `team/project1` with the numerical ID of the group I get all projects. `https://gitlab.example.com/api/v4/groups/12345/projects`
* If I replace `team/project1` with an urlencoded name of the group it shows all projects: `https://gitlab.example.com/api/v4/groups/team%2Fproject1/projects`

The Gitlab docs state that the `id` portion of the URL needs to be an ID or an urlencoded path: https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects. 

**To Reproduce**
* Add a group to the group config
* Run multi-gitter
* See error

**Expected behavior**
No error as the `/` is properly urlencoded.

**Additional context**
It is for example often useful to include detailed logs from a run with `--log-level=trace`.

**Comment by lindell** [comment]
Seems to be from this call to the xanzy/go-gitlab library.

https://github.com/lindell/multi-gitter/blob/master/internal/scm/gitlab/gitlab.go#L160.

Looking two steps further, we have.
https://github.com/xanzy/go-gitlab/blob/7c78a6c1e0a16d61cfa8b76c6759d0f9f97d8844/groups.go#L252
https://github.com/xanzy/go-gitlab/blob/7c78a6c1e0a16d61cfa8b76c6759d0f9f97d8844/groups.go#L257
https://github.com/xanzy/go-gitlab/blob/7c78a6c1e0a16d61cfa8b76c6759d0f9f97d8844/gitlab.go#L865

It seems that it should already be URL encoded with `url.PathEscape` 🤔 
I might have time to take a closer look later this week, but please take a look as well if you have the time.

**Comment by lindell** [comment]
Tried running, and the bug does not repro for me.
![image](https://user-images.githubusercontent.com/284868/225315556-811cbabb-1710-4ce7-832d-f8063a38633d.png)

Looking at the logs, it seems to be escaped correctly. 
````
GET /api/v4/groups/multi-gitter-test%2Ftest-subgroup/projects?archived=false&include_subgroups=false&page=1&per_page=100&with_merge_requests_enabled=true
````

**Comment by lindell** [comment]
Still works with yaml-based config for me. Based on it calling `url.PathEscape`, it makes sense that is should work, but something is going on for you. Is there any more context that could help?

![image](https://user-images.githubusercontent.com/284868/225420733-51cb9d7b-9d19-4abe-bbb3-ce5b12cbad4f.png)

````
request="GET /api/v4/groups/multi-gitter-test%2Ftest-subgroup/projects?archived=false&include_subgroups=false&page=1&per_page=100&with_merge_requests_enabled=true
````

**Comment by syphernl** [comment]
Thanks for looking in to this. 
Apparently the GitLab token multi-gitter was using didn't have enough permission to access other namespaces than its own. It is working fine now. My apologies!
