### ISSUE TITLE
Is there a way to pass a list of repositories?

### ISSUE THREAD

**Issue by marvindanig** [lindell/multi-gitter#380]
Like a list on a text file instead of all the repos under an org/individual? If yes, can you direct me to its specific documentation?

**Comment by marvindanig** [comment]
I looked at the README and inside the /docs folder. It wasn't there, which you already know. Coming from [git-xargs](https://github.com/gruntwork-io/git-xargs)'s documentation, I had the need on my mind when I landed on multi-gitter. 

Does this help?

> I'm assuming there isn't a way to pass an explicit list of repos to multi-gitter.

**Comment by lindell** [comment]
It might be a good idea to rename the docs folder since it might be misleading as it was for you.

What did you search for in the readme and where did you look?

It does exist there. It is called `--repo` or the config file option `repo`

**Comment by marvindanig** [comment]
Okay, some more inputs: 

On the README, I searched for things like 'pass a list,' 'list of repos,' and 'path to a list of repos'…but also I missed the `--repo` flag option on that thick wall of options that are expandable on the README. 

Would `--repos`, a plural flag for the list option be better? Would be nice for the documentation to mention the case of `--repo` somewhere. Since in most scenarios, not all repos under an org would require a horizontal change.

**Comment by lindell** [comment]
I've definitely been thinking about switching to plural for some flags, but that would have to be for a breaking release

> Since in most scenarios, not all repos under an org would require a horizontal change.

This is definitely true. But the most common scenario is to run multi-gitter on an org or similar and let the script decide if a change is needed or not by making/not making a change. If this would be something like 3/100 repos, that might be too inefficient, and and `--repo` is there if needed. :)
