### ISSUE TITLE
Feature request: Add comment

### ISSUE THREAD

**Issue by henrik242** [lindell/multi-gitter#391]
Firstly, thanks for a great tool! You should add donate options :) 

Then the feature request: It would be really useful to be able to add comments to existing pull requests (with matching branch or PR title).

It would also be nice to be able to replace the first comment (pr body) content.

```
Usage:
  multi-gitter edit [script path] [flags]

Flags:
  ...
  -b, --pr-body string             Replace the body of the PR.
  -t, --pr-title string            Replace the title of the PR.
  --comment string                 Add a comment to the PR.
  ...
 ```

**Comment by henrik242** [comment]
For others in need of this, here's how to add PR comments using the REST API:
``
#!/usr/bin/env bash

set -o pipefail -o nounset -o errexit

REPO_NAME=$1
PR_NUMBER=$2
GITHUB_TOKEN=$3

curl -s -H "Authorization: token $GITHUB_TOKEN" \
 -X POST -d '{"body": "Awesome comment"}' \
 "https://the.github.host/api/v3/repos/${REPO_NAME}/issues/${PR_NUMBER}/comments"
```

**Comment by lindell** [comment]
For updating the PR body, there is this #368 (now stale) PR to do so.
