### ISSUE TITLE
Use a file as repository input

### ISSUE THREAD

**Issue by bobo** [lindell/multi-gitter#427]
**The feature request**
add a flag
--repositories filename
where filename is a file with one repository per line.
ie:
my-org/repository1
my-org/repository2
my-other-org/repostiroy3

**My use case**
To keep track of what files have been run towards what repositories, i keep a repository with the layout

folder-with-name-of-run/command.sh
folder-with-name-of-run/repositories.sh

It is then easy to automate new runs, go back and do status runs on a specific command etc.
This can of already be done today with some bash when running the command. But it would be much cleaner to just specify a file.

**Comment by lindell** [comment]
The format you are suggesting is not possible today, but a config file with the following format is:

```config.yaml
repo:
 - my-org/repository1
 - my-org/repository2
 - my-other-org/repostiroy3
```

And then use `--config=config.yaml`

I feel that is sufficient? But please describe your use case in more detail if you think this is still needed.

**Comment by bobo** [comment]
I think that works more then well enough, thank you!
kinda feel i should have realized that, but i didnt.
