### ISSUE TITLE
Assets are mising in v0.49.1 release

### ISSUE THREAD

**Issue by fabasoad** [lindell/multi-gitter#447]
**Describe the bug**

**To Reproduce**
1. Go to the [v0.49.1](https://github.com/lindell/multi-gitter/releases/tag/v0.49.1) release page.
2. Notice only 2 assets attached:

<img width="241" alt="Screenshot 2024-01-06 at 19 02 40" src="https://github.com/lindell/multi-gitter/assets/2127723/41659b9d-120d-491b-b381-4d204bdad6d8">

**Expected behavior**
Should be 22 assets like in [previous release](https://github.com/lindell/multi-gitter/releases/tag/v0.49.0):

<img width="182" alt="Screenshot 2024-01-06 at 19 02 47" src="https://github.com/lindell/multi-gitter/assets/2127723/4c4f5846-1d75-4c53-b5c6-e3821e20da81">

**Additional context**
None.

**Comment by lindell** [comment]
The release workflow hit some rate limit. Should be fixed now.
