### ISSUE TITLE
Feature request: Add a flag to allow only pushing the Feature Branch without creating a PR, or pushing directly to an existing branch

### ISSUE THREAD

**Issue by daemocles** [lindell/multi-gitter#454]
**Feature Branch only flag**
Add a flag to the `run` command to disable creating a pull request, to only create the feature branch. 

**My use case**
In my case, I have multiple repositories which I want to run scripts against to create feature branches.
However I don't want to create a pull request to the default branch.
Instead I wish to create multiple pull requests from the feature branch to different protected branches in a sequential order.
To do this, I would like to add an option to only create the feature branch, and then create pull requests afterwards

**Implementation**
- [X] I would like to contribute this feature if it's a suitable addition to multi-gitter
- [ ] I have no intention of adding this feature myself.

**Comment by lindell** [comment]
> and then create pull requests afterwards

Do you mean to do this manually, or are you suggesting a change to enable this in multi-gitter as well?

**Comment by daemocles** [comment]
Ideally I would also like to add a separate feature to declare multiple branches to create pull requests to.

It might be better to add a feature flag to declare multiple branches to create pull requests to instead, or both if someone wanted to perform the pull requests manually

**Comment by lindell** [comment]
I'm not sure I understand your last comment. Could you please elaborate. 

But the initial feature of creating the branches without creating PR is something I think should be accepted. The question is just what to call it. We already have `skip-pr`, but it's referring to merging directly into the head branch.
