### ISSUE TITLE
Document how to pass arguments to scripts

### ISSUE THREAD

**Issue by PaulRBerg** [lindell/multi-gitter#485]
According to https://github.com/lindell/multi-gitter/pull/14, it appears that it is possible to pass arguments to scripts.

However, I don't see how that can actually be done in practice. There's no documentation for this in the README.

**Comment by lindell** [comment]
It is sort of described in the readme, via the interpreter section. 

You add arguments by running something like this
````
multi-gitter run "script argument"
````
