### ISSUE TITLE
Installation is failing on Windows

### ISSUE THREAD

**Issue by fabasoad** [lindell/multi-gitter#489]
**Describe the bug**
The following error message is shown:

```text
lindell/multi-gitter info checking GitHub for latest tag
lindell/multi-gitter debug http_download https://github.com/lindell/multi-gitter/releases/latest
lindell/multi-gitter debug http_download_curl received HTTP status 000
lindell/multi-gitter crit unable to find '' - use 'latest' or see https://github.com/lindell/multi-gitter/releases for details
Error: Process completed with exit code 1.
```

**To Reproduce**
1. Go to the latest [Test install.sh](https://github.com/lindell/multi-gitter/actions/runs/9748232256/job/26902784865) job.
2. See the result.

**Expected behavior**
Installation should pass successfully.

**Additional context**
It seems it is started failing [on June 8](https://github.com/lindell/multi-gitter/actions/runs/9420343945).

**Comment by lindell** [comment]
This seems to be fixed. Closing. Please let be know if you still have problems.
