### ISSUE TITLE
BitBucket cloud support

### ISSUE THREAD

**Issue by lindell** [lindell/multi-gitter#99]
BitBucket is one of the biggest SCMs after GitHub and GitLab and support for it would be useful for a lot of people. 

If anyone is familiar with BitBucket and is willing to help out. The `VersionController` interface can be implemented and be placed in this package: https://github.com/lindell/multi-gitter/tree/master/internal/scm

**Update:** Thanks to @ryancurrah mutli-gitter now have bitbucket-server support since [v0.33.0](https://github.com/lindell/multi-gitter/releases/tag/v0.33.0). It still missed BitBucket cloud support, making this ticket still relevant.

**Comment by gcase555** [comment]
I am interested in working on this, going to take a try and share my progress

**Comment by gcase555** [comment]
Mini-update: I got started implementing the interfaces and have been using https://github.com/ktrysmt/go-bitbucket for bitbucket cloud API calls, I need to do more testing and finish implementing the rest of the needed methods. I think I should have a pull-request submitted within the next few weeks unless I run into any blockers.

**Comment by lindell** [comment]
Great to hear that you are progressing! If you need any clarification or help, feel free to reach out ☺️

Are there people here that are willing to beta-test @gcase555 's changes once they are ready?

**Comment by gcase555** [comment]
I do know some bitbucket cloud users, I can have them test it out and leave feedback here once its ready for testing.

**Comment by gcase555** [comment]
mini-update: we have implemented most of the required methods for the interface and are currently doing some more testing. We have tested most of the functionality works including the ability to mass create/merge/close PRs and the methods for fetching repositories in bitbucket cloud.

Our fork is over at https://github.com/gcase555/multi-gitter and we will be submitting a PR within the next week or two with the code we have got.

**Comment by gcase555** [comment]
update: we refactored and cleaned up our pull-request with most of the changes requested and the fork we have now is in a usable state https://github.com/asecurityteam/multi-gitter

We are hoping to get the pull-request merged and be able to close out this issue 🤞
